
image:
  repository: sammielas/fintech-app
  pullPolicy: Always
  containerName: "fintech-app-dev"
  tag: ce1b873
service:
  port: 3000
secrets:
  jwtSecretName: jwt-secret
  jwtSecretKey: jwt
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"